#!/bin/sh

originalBranch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
echo -e "on branch: $originalBranch"

if [ $originalBranch != "production" ]; then
	git checkout production
fi

git pull origin production
echo -e "Attempting to build BLocal.Web.Mvc3"
rake -f ${PWD}/rakefile manager:build

if [ $originalBranch != "production" ]; then
	git checkout $originalBranch
fi